### ISSUE TITLE
Adding comments?

### ISSUE THREAD

**Issue by seongbae** [INsReady/DrupalCloud#10]
I've been trying to add ability to create new comments.  I insert token that I get from logging in into the HTTP header when I send save comment request... but it's not working.  Has anyone been successful with adding contents such as node or comment?

Thanks.

**Comment by skyred** [comment]
I would assume you used RESTServerClient, which hasn't finished implemented comment\* methods. Take a look at JSONServerClient, it has comment\* methods implementation. Maybe, if you have time, contribute your code back.
