### ISSUE TITLE
[INFO] I implemented another drupal rest/services client with retrofit for android: drupalfit

### ISSUE THREAD

**Issue by yongjhih** [INsReady/DrupalCloud#11]
https://github.com/yongjhih/drupalfit
I think its helpful to inspire.

**Comment by skyred** [comment]
@yongjhih I am also planning on re-writing the whole library from scratch, by supporting RESTful Web Services module, which is in core in Drupal 8. and it will be based on Android Studio instead of Eclipse. 

I don't see much library code in your project yet, only a Sample activity. Maybe, you could publish more code to share?

**Comment by yongjhih** [comment]
@skyred It's good news to do support RESTful Web Services module for Drupal 8 from you.

The drupalfit is not completed now, so it's welcomed contribution. It's easy to implement new RESTful Services with retrofit.

For example to get a Node:
1. Interface of Drupal8Service.java:

``` java
    @GET("/entity/node/{id}")
    Node getNode(
        @Path("id") long id
    );

    @Keep
    @KeepClassMembers
    @JsonIgnoreProperties(ignoreUnknown = true)
    public static class Node {
         public Node() {
         }
         public long nid;
         public String title;
    }
```
1. Instance of Service:

``` java
DrupalService service = new RestAdapter.Builder().setEndpoint("https://example.com/api").setXXX().build().create(Drupal8Service.class);
Node node1 = service.getNode(1);
```

Thats it. Is it powerful? I could add you as collaborator for drupalfit if you want.

**Comment by skyred** [comment]
I haven't heard retrofit before. But, it sounds really interesting. Let me take a look first. Thanks for letting me know.

**Comment by yongjhih** [comment]
@skyred I have updated drupalfit.

**Comment by skyred** [comment]
I would like to make Authentication modular; in other words, we can support No Authentication, Basic Auth, OAuth2, Hawk, OZ or custom authentication. But, of course, we don't have to support all of these out of box, the modular structure is more important. 

@yongjhih Is this something that you would like to add in your project?

**Comment by yongjhih** [comment]
@skyred It sounds good. I'll be glad to see it be added into drupalfit project.

**Comment by yongjhih** [comment]
@skyred drupalfit has supported addComment and X-CSRF-Token

**Comment by skyred** [comment]
Retrofit is a good library, but it has its own limitation at the moment, for example, it is really hard to support hypermedia in Drupal 8. 

OKHttp library is also very interesting, especially it supports SPDY.

**Comment by xuxucode** [comment]
I am very interesting in your DrupalCon Austin2014 session of DRUPAL POWERED ANDROID NATIVE TABLET APP AND MOBILE COMMERCE, where to  find the video?

**Comment by skyred** [comment]
@edwardaa I didn't present in Austin, but you can see my video for Denver 2013; however Denver video has a different focus.

**Comment by xuxucode** [comment]
@skyred Thanks. I am an Android & Drupal developer, but a newbie in the E-commerce world, which method you choose for E-commerce projects for Android apps, totally native or hybrid or something else? any help will be appreciated.

**Comment by skyred** [comment]
@edwardaa I only build native app, because native app opens the door to building some unique and optimized for mobile. 

For eCommerce, I used restws module https://www.drupal.org/project/restws; the future version of DrupalCould will on only support RESTws instead of Services module.
