### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by internalG** [INsReady/DrupalCloud#13]
It seems it's the only Android client lib for Drupal. So does it still work for D7 with latest services module?

**Comment by skyred** [comment]
This project hasn't been maintained for years. Long story in short, if you use D8.3 + JSONAPI on the server end, then use https://github.com/kamikat/moshi-jsonapi, it is much much faster and better than this project can achieve.

**Comment by internalG** [comment]
Thanks. And for D7+service3.x with android, do you have better recommendations?

**Comment by skyred** [comment]
For D7, I switched from using services module to restws module. Then, on Android, I just bypassed DrupalCloud, and used Retrofit (https://github.com/square/retrofit) directly

**Comment by internalG** [comment]
Thanks for your helpful information!
