### ISSUE TITLE
CSRF Token Compatibility 

### ISSUE THREAD

**Issue by ghost** [INsReady/DrupalCloud#5]
The library doesn't offer any support for the new csrf Token (introduced with services 3.2).

Fix would be nice.

**Comment by skyred** [comment]
The patch committed to services is https://drupal.org/node/2016501
Security annoucement https://drupal.org/node/2012982
Change record: CSRF validation https://drupal.org/node/2018963

**Comment by skyred** [comment]
CSRF token has been supported for a while.
