### ISSUE TITLE
DrupalCloud and JSONserverclient (Android)

### ISSUE THREAD

**Issue by Yiphi** [INsReady/DrupalCloud#7]
Hello.

I'm trying to write an Android app for my Drupal site (already wrote one for iOS using Drupal iOS SDK--it works great). When trying to run/compile the code below, I get null pointer exceptions/construct undefined errors. Of note, both lines are implemented within the public void(OnClick) functions.

Null pointer runtime exception: JSONServerClient sandbox = new JSONServerClient(null, getString(R.string.sharedpreferences_name), getString(R.string.SERVER), getString(R.string.API_KEY), getString(R.string.DOMAIN), getString(R.string.ALGORITHM), Long.parseLong(getString(R.string.SESSION_LIFETIME)));

try{
loginResult = sandbox.userLogin(usernameXMLasText, passwordXMLasText);
Log.e(loginResult, "login successful");
} 

catch (ServiceNotAvailableException e) {
e.printStackTrace();
Log.e(loginResult, "login unsuccessful");
}

Construct undefined compiler error: JSONServerClient sandbox = new JSONServerClient(this, getString(R.string.sharedpreferences_name), getString(R.string.SERVER), getString(R.string.API_KEY), getString(R.string.DOMAIN), getString(R.string.ALGORITHM), Long.parseLong(getString(R.string.SESSION_LIFETIME)));

try{
loginResult = sandbox.userLogin(usernameXMLasText, passwordXMLasText);
Log.e(loginResult, "login successful");
} 

catch (ServiceNotAvailableException e) {
e.printStackTrace();
Log.e(loginResult, "login unsuccessful");
}

Question: How should I implement/call JSONserverclient to connect to my Drupal site to login and download JSON views?

Thank you in advance for your help.

**Comment by skyred** [comment]
JSONServiceClient is only for JSONServer on the Drupal site, which is only avaiable for D6. If you use D7, you should use RESTServerClient.

**Comment by Yiphi** [comment]
Hi skyred--thank you for the prompt response!!!

I apologize for not being clear in my question.  I have the JSON service working perfectly on my Drupal 6 site.  In fact, I wrote an iOS app using Drupal iOS SDK that connects to my Drupal site and downloads views data successfully.

My question now is, "How do I accomplish the same task using DrupalCloud for the Android version of my app?"  The code above either doesn't run or doesn't compile.  As such, I can't even get to the point of successfully connecting to my Drupal site with the JSONserverclient functions/class built into the DrupalCloud library.

I hope that makes sense.  And, thank you again for your help.

**Comment by skyred** [comment]
You are still unclear on your server choice. Did you use REST server or JSONServer? they both support json format. 

anyway, for D6, DrupalCloud only supported JSONserver, which worked with Services 2, which is unsupported now.

**Comment by Yiphi** [comment]
Thank you, skyred.

I am using JSONServer (via Services 3) on Drupal 6.  And, this works beautifully with my iOS app (using Drupal iOS SDK from Kyle Browning).  That being said, if I'm reading your last post correctly, does DrupalCloud not work with Services 3?

Thanks again for your help.

**Comment by skyred** [comment]
JSONserver does NOT support Services 3, as I just updated the project status. DrupalCloud supports Services 3 (which implies that you have to use REST)

**Comment by Yiphi** [comment]
Thank you, skyred--that information is extremely helpful.

So, to summarize:  If I am using Drupal 6 and Services 3, I can use DrupalCloud to connect my Android app to my Drupal site if I use REST.  Is that correct?  If so, do you have any documentation that you recommend that I should use to do this (hopefully a step by step guide)?

Thanks again for your help.  You are extremely helpful and thorough.

**Comment by skyred** [comment]
In theory, yes. But, I have not tested D6 + Services 3 + RESTServerClient (DrupalCloud) at all. 
I have only extensively used 
1. D6 + Services 2 + JSONServer
2. D7 + Services 3 + RESTServer

This public repo is all I have for now. But, we are still slowly committing new things including documentation to this repo

**Comment by Yiphi** [comment]
Perfect--thank you, skyred.  It looks like I'm going to have to read up on REST.  I hope I can get it to work.  Thank you for all your help, sir.
